name: Bakwasfile
on: push
jobs:
  build:              # this is the job name which u created inside your workflow 
    runs-on: ubuntu-latest
    steps: 
     - name: checkout code from repo
       uses: actions/checkout@v4
     - name: List files in repository
       run: ls -R

  #  deploy:
  #  runs-on: ubuntu-latest
   # steps:
   #   - name: Checkout the code from Repo
  #      uses: actions/checkout@v4
  #    - name: Configure AWS Credentials
 #       uses: aws-actions/configure-aws-credentials@v4
  #      with: 
  #        aws-access-key-Id: ${{secrets.AWS_ACCESS_KEY_ID}}
  #       aws-access-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  #        aws-region: eu-west-1 
          

  
     
